# Generated by Django 4.1 on 2022-09-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder', '0002_curso_entregable_estudiantes_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiantes',
            new_name='estudiantes1',
        ),
    ]
