# Generated by Django 4.1 on 2022-10-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoder', '0004_rename_estudiantes1_estudiantes_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('camada', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='estudiantes',
            new_name='estudiantes1',
        ),
    ]
